jobs:
  assign-milestone:
    if: github.event.issue.state_reason == 'completed'
    permissions:
      contents: write
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: "const fs = require('fs')\nconst version = fs.readFileSync('sdks/python/apache_beam/version.py',\
          \ {encoding: 'utf-8'})\nconst versionArray = version.split('.')\nconst minorVersion\
          \ = versionArray[versionArray.length-3]\n\nconsole.log(`Beam fix version:\
          \ 2.${minorVersion}.0`)\n\nlet milestones = await github.rest.issues.listMilestones({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  state: 'open',\n\
          })\n\nlet filteredMilestones =  milestones.data.filter(m => m.title.indexOf(`2.${minorVersion}.0`)\
          \ > -1)\n\nif (filteredMilestones.length > 1) {\n  throw new Exception(`Invalid\
          \ milestone. More than one milestone exists for 2.${minorVersion}.0`)\n\
          }\n\nif (filteredMilestones.length == 0) {\n  await github.rest.issues.createMilestone({\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    title:\
          \ `2.${minorVersion}.0 Release`,\n  });\n\n  milestones = await github.rest.issues.listMilestones({\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    state:\
          \ 'open',\n  })\n\n  filteredMilestones =  milestones.data.filter(m => m.title.indexOf(`2.${minorVersion}.0`)\
          \ > -1)\n}\n\nconst curMilestone = filteredMilestones[0]\n\nconst issue\
          \ = await github.rest.issues.update({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  milestone:\
          \ curMilestone.number,\n})\nconsole.log(issue)\n"
name: Assign Milestone on issue close
on:
  repository_dispatch:
    types: trigger-ga___assign_milestone.yml
