concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_LoadTests_Python_SideInput_Dataflow_Batch:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Python SideInput Dataflow Batch''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: default
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_1gb_1window_1key_percent_dict.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_1gb_1window_99key_percent_dict.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_10gb_1window_first_iterable.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_10gb_1window_iterable.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_1gb_1window_first_list.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_1gb_1window_list.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_1gb_1000window_1key_percent_dict.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_1gb_1000window_99key_percent_dict.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_10gb_1000window_first_iterable.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_SideInput_Dataflow_Batch_10gb_1000window_iterable.txt

          '
        test-language: python
        test-type: load
    - continue-on-error: true
      id: datetime
      name: Set current datetime
      run: 'echo "datetime=$(date ''+%m%d%H%M%S'' --utc)" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 1 (1gb-1kb-10workers-1window-1key-percent-dict)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_1
          }} --job_name=load-tests-python-dataflow-batch-sideinput-1-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 2 (1gb-1kb-10workers-1window-99key-percent-dict)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_2
          }} --job_name=load-tests-python-dataflow-batch-sideinput-2-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 3 (10gb-1kb-10workers-1window-first-iterable)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_3
          }} --job_name=load-tests-python-dataflow-batch-sideinput-3-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 4 (10gb-1kb-10workers-1window-iterable)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_4
          }} --job_name=load-tests-python-dataflow-batch-sideinput-4-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 5 (1gb-1kb-10workers-1window-first-list)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_5
          }} --job_name=load-tests-python-dataflow-batch-sideinput-5-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 6 (1gb-1kb-10workers-1window-list)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_6
          }} --job_name=load-tests-python-dataflow-batch-sideinput-6-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 7 (1gb-1kb-10workers-1000window-1key-percent-dict)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_7
          }} --job_name=load-tests-python-dataflow-batch-sideinput-7-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 8 (1gb-1kb-10workers-1000window-99key-percent-dict)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_8
          }} --job_name=load-tests-python-dataflow-batch-sideinput-8-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 9 (10gb-1kb-10workers-1000window-first-iterable)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_9
          }} --job_name=load-tests-python-dataflow-batch-sideinput-9-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run SideInput Dataflow Batch Python Load Test 10 (10gb-1kb-10workers-1000window-iterable)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.sideinput_test
          \

          -Prunner=DataflowRunner \

          -PpythonVersion=3.8 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_SideInput_Dataflow_Batch_test_arguments_10
          }} --job_name=load-tests-python-dataflow-batch-sideinput-10-${{ steps.datetime.outputs.datetime
          }}'''
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Python_SideInput_Dataflow_Batch
        job_phrase:
        - Run Load Tests Python SideInput Dataflow Batch
    timeout-minutes: 720
name: LoadTests Python SideInput Dataflow Batch
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Python_SideInput_Dataflow_Batch.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
