concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.sender.login }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_IODatastoresCredentialsRotation:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')

      '
    name: ${{ matrix.job_name }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Starting credential rotation
      run: 'gcloud container clusters update io-datastores --start-credential-rotation
        --zone=us-central1-a --quiet

        '
    - continue-on-error: true
      name: Rebuilding the nodes
      run: 'gcloud container clusters upgrade io-datastores --node-pool=pool-1 --zone=us-central1-a
        --quiet

        '
    - continue-on-error: true
      name: Completing the rotation
      run: 'gcloud container clusters update io-datastores --complete-credential-rotation
        --zone=us-central1-a --quiet

        '
    - continue-on-error: true
      if: failure()
      name: Generate Date
      run: 'date=$(date -u +"%Y-%m-%d")

        echo "date=$date" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: failure()
      name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        body: 'Something went wrong during the automatic credentials rotation for
          IO-Datastores Cluster, performed at ${{ env.date }}. It may be necessary
          to check the state of the cluster certificates. For further details refer
          to the following links:\n * Failing job: https://github.com/apache/beam/actions/workflows/beam_IODatastoresCredentialsRotation.yml
          \n * Job configuration: https://github.com/apache/beam/blob/master/.github/workflows/beam_IODatastoresCredentialsRotation.yml
          \n * Cluster URL: https://pantheon.corp.google.com/kubernetes/clusters/details/us-central1-a/io-datastores/details?mods=dataflow_dev&project=apache-beam-testing'
        from: gactions@beam.apache.org
        password: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_PASSWORD }}
        secure: true
        server_address: smtp.gmail.com
        server_port: 465
        subject: Credentials Rotation Failure on IO-Datastores cluster (${{ env.date
          }})
        to: dev@beam.apache.org
        username: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_ADDRESS }}
    strategy:
      matrix:
        job_name:
        - beam_IODatastoresCredentialsRotation
        job_phrase:
        - N/A
    timeout-minutes: 100
name: Rotate IO-Datastores Cluster Credentials
on:
  repository_dispatch:
    types: trigger-ga___beam_IODatastoresCredentialsRotation.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
