concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.sender.login }}
env:
  BEAM_ROOT_DIR: /runner/_work/beam/beam
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_Playground_CI_Nightly:
    if: 'github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')

      '
    name: beam_Playground_CI_Nightly
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: default
    - continue-on-error: true
      name: Install requirements
      run: 'cd $BEAM_ROOT_DIR/playground/infrastructure

        pip install -r requirements.txt

        '
    - continue-on-error: true
      name: Get Beam latest release
      run: 'BEAM_VERSION=$(curl -s https://api.github.com/repos/apache/beam/releases/latest
        | jq -r ''.tag_name'')

        echo "BEAM_VERSION=${BEAM_VERSION#v}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: ${{ matrix.sdk == 'python' }}
      name: Build PYTHON base
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        gradle-command: :sdks:python:container:py310:docker -Pdocker-tag=nightly -Pdocker-pull-licences=true
    - continue-on-error: true
      name: Build SDK container
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        gradle-command: :playground:backend:containers:${{ matrix.sdk }}:docker -Pdocker-tag=nightly
          -Psdk-tag=$BEAM_VERSION -Pdocker-pull-licences=true
    - continue-on-error: true
      name: Run SDK container
      run: 'CONTAINER_ID=$(docker run -d -e PROTOCOL_TYPE=TCP apache/beam_playground-backend-${{
        matrix.sdk }}:nightly)

        echo "container_id=$CONTAINER_ID" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Get Container IP
      run: 'CONTAINER_IP=$(docker inspect -f ''{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}''
        ${{ env.container_id }})

        echo "container_ip=$CONTAINER_IP" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        BEAM_EXAMPLE_CATEGORIES: ${{ env.BEAM_ROOT_DIR }}/playground/categories.yaml
        SDK: ${{ matrix.sdk }}
        SERVER_ADDRESS: ${{ env.container_ip }}:8080
      name: Run CI
      run: 'cd $BEAM_ROOT_DIR/playground/infrastructure

        python ci_cd.py --step CI --sdk SDK_${SDK^^} --origin PG_EXAMPLES --subdirs
        ./learning/katas ./examples ./sdks

        '
    strategy:
      fail-fast: false
      matrix:
        sdk:
        - python
        - java
        - go
name: Playground CI Nightly
on:
  repository_dispatch:
    types: trigger-ga___beam_Playground_CI_Nightly.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
