concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_Java_BigQueryEarlyRollout:
    if: 'github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Java BigQueryEarlyRollout PostCommit''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: run PostCommit Java BigQueryEarlyRollout script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        gradle-command: :sdks:java:io:google-cloud-platform:bigQueryEarlyRolloutIntegrationTest
    - continue-on-error: true
      if: failure()
      name: Generate Date
      run: 'date=$(date -u +"%Y-%m-%d")

        echo "date=$date" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: failure()
      name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        body: 'PostCommit Java BigQueryEarlyRollout failed on ${{ env.date }}. This
          test monitors BigQuery rollouts impacting Beam and should be escalated immediately
          if a real issue is encountered to pause further rollouts. For further details
          refer to the following links:\n * Failing job: https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_BigQueryEarlyRollout.yml
          \n * Job configuration: https://github.com/apache/beam/blob/master/.github/workflows/beam_PostCommit_Java_BigQueryEarlyRollout.yml

          '
        from: gactions@beam.apache.org
        password: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_PASSWORD }}
        secure: true
        server_address: smtp.gmail.com
        server_port: 465
        subject: BigQueryEarlyRollout Beam Failure (${{ env.date }}) - investigate
          and escalate quickly
        to: datapls-plat-team@google.com
        username: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_ADDRESS }}
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/build/test-results/**/*.xml'
    strategy:
      matrix:
        job_name:
        - beam_PostCommit_Java_BigQueryEarlyRollout
        job_phrase:
        - Run Java BigQueryEarlyRollout PostCommit
    timeout-minutes: 100
name: PostCommit Java BigQueryEarlyRollout
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Java_BigQueryEarlyRollout.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
