concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_PerformanceTests_WordCountIT_PythonVersions:
    if: "github.event_name == 'workflow_dispatch' ||\n(github.event_name == 'schedule'\
      \ && github.repository == 'apache/beam') ||\n(startswith(github.event.comment.body,\
      \ 'Run Python') &&\n  endswith(github.event.comment.body, 'WordCountIT Performance\
      \ Test'))\n"
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.python_version
      }} ${{ matrix.job_phrase_2 }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase_1 }} ${{ matrix.python_version }} ${{
          matrix.job_phrase_2 }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.python_version
          }} ${{ matrix.job_phrase_2 }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: ${{ matrix.python_version }}
    - continue-on-error: true
      id: set_py_ver_clean
      name: Set PY_VER_CLEAN
      run: 'PY_VER=${{ matrix.python_version }}

        PY_VER_CLEAN=${PY_VER//.}

        echo "py_ver_clean=$PY_VER_CLEAN" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/performance-tests-pipeline-options/wordCountIT_Python.txt

          '
        arguments: '--job_name=performance-tests-wordcount-python${{steps.set_py_ver_clean.outputs.py_ver_clean}}-batch-1gb$(date
          ''+%m%d%H%M%S'' --utc)

          --metrics_table=wordcount_py${{steps.set_py_ver_clean.outputs.py_ver_clean}}_pkb_results

          --influx_measurement=wordcount_py${{steps.set_py_ver_clean.outputs.py_ver_clean}}_results

          '
        test-language: python
        test-type: load
    - continue-on-error: true
      name: Run test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--info \

          -Ptest=apache_beam/examples/wordcount_it_test.py::WordCountIT::test_wordcount_it
          \

          "-Ptest-pipeline-options=${{ env.beam_PerformanceTests_WordCountIT_PythonVersions_test_arguments_1
          }}"

          '
        gradle-command: :sdks:python:test-suites:dataflow:py${{steps.set_py_ver_clean.outputs.py_ver_clean}}:runPerformanceTest
    - continue-on-error: true
      if: failure()
      name: Archive Python Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Python Test Results
        path: '**/pytest*.xml'
    - continue-on-error: true
      if: always()
      name: Publish Python Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/pytest*.xml'
    strategy:
      fail-fast: false
      matrix:
        job_name:
        - beam_PerformanceTests_WordCountIT_PythonVersions
        job_phrase_1:
        - Run Python
        job_phrase_2:
        - WordCountIT Performance Test
        python_version:
        - '3.8'
    timeout-minutes: 100
name: PerformanceTests WordCountIT PythonVersions
on:
  repository_dispatch:
    types: trigger-ga___beam_PerformanceTests_WordCountIT_PythonVersions.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
