concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_Publish_BeamMetrics:
    if: 'github.event_name == ''push'' ||

      github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Beam Metrics Deployment''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Setup credential helper
      run: 'gcloud auth configure-docker

        '
    - continue-on-error: true
      name: run Beam Metrics deployment script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PKUBE_CONFIG_PATH=''$HOME/.kube/config''

          '
        gradle-command: :beam-test-infra-metrics:getClusterCredentials :beam-test-infra-metrics:deploy
    strategy:
      matrix:
        job_name:
        - beam_PostCommit_BeamMetrics_Publish
        job_phrase:
        - Run Beam Metrics Deployment
    timeout-minutes: 100
name: Publish BeamMetrics
on:
  repository_dispatch:
    types: trigger-ga___beam_Publish_BeamMetrics.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
