concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PreCommit_Java:
    if: 'github.event_name == ''push'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event_name == ''workflow_dispatch'' ||

      github.event.comment.body == ''Run Java PreCommit''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: run Java PreCommit script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PdisableSpotlessCheck=true \

          -PdisableCheckStyle=true \

          -PenableJacocoReport \

          '
        gradle-command: :javaPreCommit
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/build/test-results/**/*.xml'
    - continue-on-error: true
      if: always()
      name: Archive SpotBugs Results
      uses: actions/upload-artifact@v4
      with:
        name: SpotBugs Results
        path: '**/build/reports/spotbugs/*.html'
    - continue-on-error: true
      if: always()
      name: Publish SpotBugs Results
      uses: jwgmeligmeyling/spotbugs-github-action@v1.2
      with:
        name: Publish SpotBugs
        path: '**/build/reports/spotbugs/*.html'
    - continue-on-error: true
      name: Archive Jacoco Results
      uses: actions/upload-artifact@v4
      with:
        name: Jacoco Results
        path: '**/build/jacoco/report/**'
    - continue-on-error: true
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: java
    strategy:
      fail-fast: false
      matrix:
        job_name:
        - beam_PreCommit_Java
        job_phrase:
        - Run Java PreCommit
    timeout-minutes: 120
name: PreCommit Java
on:
  repository_dispatch:
    types: trigger-ga___beam_PreCommit_Java.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
