concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_Java_SingleStoreIO_IT:
    if: 'github.event_name == ''push'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      github.event.comment.body == ''Run Java SingleStoreIO_IT''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      id: auth
      name: Authenticate on GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - continue-on-error: true
      name: Set k8s access
      uses: ./.github/actions/setup-k8s-access
      with:
        cluster_name: io-datastores
        k8s_namespace: ${{ matrix.job_name }}-${{ github.run_id }}
        remove_finalizer: memsqlclusters.memsql.com/sdb-cluster
    - continue-on-error: true
      name: Install Singlestore operator
      run: 'kubectl apply -f ${{github.workspace}}/.test-infra/kubernetes/singlestore/sdb-rbac.yaml

        kubectl apply -f ${{github.workspace}}/.test-infra/kubernetes/singlestore/sdb-cluster-crd.yaml

        kubectl apply -f ${{github.workspace}}/.test-infra/kubernetes/singlestore/sdb-operator.yaml

        kubectl wait --for=condition=Ready pod -l name=sdb-operator --timeout=120s

        '
    - continue-on-error: true
      id: install_singlestore
      name: Install Singlestore cluster
      run: "kubectl apply -f ${{github.workspace}}/.test-infra/kubernetes/singlestore/sdb-cluster.yaml\n\
        kubectl wait --for=jsonpath='{.status.phase}'=Running memsqlclusters.memsql.com\
        \ --all --timeout=120s\nkubectl wait svc/svc-sdb-cluster-ddl --for=jsonpath='{.status.loadBalancer.ingress[0].ip}'\
        \ --timeout=120s\nloadbalancer_IP=$(kubectl get svc svc-sdb-cluster-ddl -o\
        \ jsonpath='{.status.loadBalancer.ingress[0].ip}') \necho lb_ip=$loadbalancer_IP\
        \ >> $GITHUB_OUTPUT\n"
    - continue-on-error: true
      name: Run Java SingleStore IO IT
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: --info -DintegrationTestRunner=dataflow -DintegrationTestPipelineOptions='["--tempRoot=gs://temp-storage-for-perf-tests","--project=apache-beam-testing","--runner=DataflowRunner","--singleStoreUsername=admin","--singleStorePassword=secretpass","--singleStorePort=3306","--numberOfRecords=1000",
          "--singleStoreServerName=${{ steps.install_singlestore.outputs.lb_ip }}"]'
        gradle-command: :sdks:java:io:singlestore:integrationTest --tests org.apache.beam.sdk.io.singlestore.SingleStoreIODefaultMapperIT
          :sdks:java:io:singlestore:integrationTest --tests org.apache.beam.sdk.io.singlestore.SingleStoreIOSchemaTransformIT
          :sdks:java:io:singlestore:integrationTest --tests org.apache.beam.sdk.io.singlestore.SingleStoreIOConnectionAttributesIT
    strategy:
      fail-fast: false
      matrix:
        job_name:
        - beam_PostCommit_Java_SingleStoreIO_IT
        job_phrase:
        - Run Java SingleStoreIO_IT
    timeout-minutes: 100
name: PostCommit Java SingleStoreIO IT
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Java_SingleStoreIO_IT.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
