concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_XVR_JavaUsingPython_Dataflow:
    if: 'github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run XVR_JavaUsingPython_Dataflow PostCommit''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.python_version
      }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }} ${{ matrix.python_version }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.python_version
          }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: '3.8

          ${{ matrix.python_version }}

          '
    - continue-on-error: true
      name: run PostCommit XVR JavaUsingPython Dataflow script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PpythonVersion=${{ matrix.python_version }} \

          '
        gradle-command: :runners:google-cloud-dataflow-java:validatesCrossLanguageRunnerJavaUsingPython
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/build/test-results/**/*.xml'
    strategy:
      matrix:
        job_name:
        - beam_PostCommit_XVR_JavaUsingPython_Dataflow
        job_phrase:
        - Run XVR_JavaUsingPython_Dataflow PostCommit
        python_version:
        - '3.8'
        - '3.12'
    timeout-minutes: 100
name: PostCommit XVR JavaUsingPython Dataflow
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_XVR_JavaUsingPython_Dataflow.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
