concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_Sickbay_Python:
    if: "github.event_name == 'workflow_dispatch' ||\ngithub.event_name == 'pull_request_target'\
      \ ||\n(github.event_name == 'schedule' && github.repository == 'apache/beam')\
      \ ||\n(startswith(github.event.comment.body, 'Run Python') &&\n   endswith(github.event.comment.body,\
      \ 'PostCommit Sickbay'))\n"
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.python_version
      }} ${{ matrix.job_phrase_2 }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase_1 }} ${{ matrix.python_version }} ${{
          matrix.job_phrase_2 }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.python_version
          }} ${{ matrix.job_phrase_2 }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: ${{ matrix.python_version }}
    - continue-on-error: true
      id: set_py_ver_clean
      name: Set PY_VER_CLEAN
      run: 'PY_VER=${{ matrix.python_version }}

        PY_VER_CLEAN=${PY_VER//.}

        echo "py_ver_clean=$PY_VER_CLEAN" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: run PostCommit Python ${{ matrix.python_version }} script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PpythonVersion=${{ matrix.python_version }} \

          '
        gradle-command: :sdks:python:test-suites:dataflow:py${{steps.set_py_ver_clean.outputs.py_ver_clean}}:postCommitSickbay
    - continue-on-error: true
      if: failure()
      name: Archive Python Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Python Test Results
        path: '**/pytest*.xml'
    - continue-on-error: true
      if: always()
      name: Publish Python Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/pytest*.xml'
    strategy:
      fail-fast: false
      matrix:
        job_name:
        - beam_PostCommit_Sickbay_Python
        job_phrase_1:
        - Run Python
        job_phrase_2:
        - PostCommit Sickbay
        python_version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    timeout-minutes: 180
name: PostCommit Sickbay Python
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Sickbay_Python.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
