concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_Metrics_Report:
    if: "(\n  (github.event_name == 'schedule' && github.repository == 'apache/beam')\n\
      \  || github.event_name == 'workflow_dispatch'\n)\n"
    name: beam_Metrics_Report
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: default
    - continue-on-error: true
      env:
        INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
        INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
      name: Run Metrics Report
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: --info -PinfluxDb=beam_test_metrics  -PinfluxHost='10.128.0.96'
          -PinfluxPort=8086
        gradle-command: :beam-test-jenkins:generateMetricsReport
    - continue-on-error: true
      name: Archive Report
      uses: actions/upload-artifact@v4
      with:
        name: Metrics Report
        path: ${{ github.workspace }}/.test-infra/jenkins/metrics_report/beam-metrics_report.html
    - continue-on-error: true
      name: Generate Date
      run: 'date=$(date -u +"%Y-%m-%d")

        echo "date=$date" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        from: beamactions@gmail.com
        html_body: file://${{ github.workspace }}/.test-infra/jenkins/metrics_report/beam-metrics_report.html
        password: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_PASSWORD }}
        secure: true
        server_address: smtp.gmail.com
        server_port: 465
        subject: Beam Metrics Report ${{ env.date }}
        to: dev@beam.apache.org
        username: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_ADDRESS }}
    timeout-minutes: 100
name: Beam Metrics Report
on:
  repository_dispatch:
    types: trigger-ga___beam_Metrics_Report.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
