concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_Java_InfluxDbIO_IT:
    if: '(github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      github.event.comment.body == ''Run Java InfluxDbIO_IT''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      id: auth
      name: Authenticate on GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - continue-on-error: true
      name: Set k8s access
      uses: ./.github/actions/setup-k8s-access
      with:
        cluster_name: io-datastores
        k8s_namespace: ${{ matrix.job_name }}-${{ github.run_id }}
    - continue-on-error: true
      id: install_influxdb
      name: Install InfluxDB
      run: "kubectl apply -f ${{ github.workspace }}/.test-infra/kubernetes/influxdb/influxdb.yml\n\
        kubectl wait --timeout 2m svc/influxdb-load-balancer-service --for=jsonpath='{.status.loadBalancer.ingress[0].ip}'\n\
        loadbalancer_IP=$(kubectl get svc influxdb-load-balancer-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')\
        \ \necho influxdb_IP=$loadbalancer_IP >> $GITHUB_OUTPUT\n"
    - continue-on-error: true
      name: Run Java InfluxDbIO_IT
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: --info -DintegrationTestRunner=direct -DintegrationTestPipelineOptions='["--influxDBURL=http://${{
          steps.install_influxdb.outputs.influxdb_IP }}:8086","--influxDBUserName=superadmin","--influxDBPassword=supersecretpassword","--databaseName=db1"]'
        gradle-command: :sdks:java:io:influxdb:integrationTest --tests org.apache.beam.sdk.io.influxdb.InfluxDbIOIT
    strategy:
      matrix:
        job_name:
        - beam_PostCommit_Java_InfluxDbIO_IT
        job_phrase:
        - Run Java InfluxDbIO_IT
    timeout-minutes: 100
name: PostCommit Java InfluxDbIO Integration Test
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Java_InfluxDbIO_IT.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
