concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  gcsbucket: apache-beam-website-pull-requests
  ghprbPullId: null
jobs:
  beam_PreCommit_Website_Stage_GCS:
    if: 'github.event_name == ''push'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event_name == ''workflow_dispatch'' ||

      github.event.comment.body == ''Run Website_Stage_GCS PreCommit''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Echo PR number
      run: echo "ghprbPullId=${{ github.event.pull_request.number || github.event.issue.number
        }}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: default
        python-version: default
    - continue-on-error: true
      name: Run website_stageWebsite script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: -PwebsiteBucket=$gcsbucket
        gradle-command: :website:stageWebsite
    - continue-on-error: true
      if: env.ghprbPullId != null
      name: Add website link to the summary if pr
      run: echo "Website published to http://$gcsbucket.storage.googleapis.com/$ghprbPullId/index.html"
        >> $GITHUB_STEP_SUMMARY
    - continue-on-error: true
      if: env.ghprbPullId == null
      name: Add website link to the summary
      run: 'USERNAME="$(whoami)"

        echo "Website published to http://$gcsbucket.storage.googleapis.com/$USERNAME-${GITHUB_REF##*/}/index.html"
        >> $GITHUB_STEP_SUMMARY

        '
    strategy:
      matrix:
        job_name:
        - beam_PreCommit_Website_Stage_GCS
        job_phrase:
        - Run Website_Stage_GCS PreCommit
    timeout-minutes: 120
name: PreCommit Website Stage GCS
on:
  repository_dispatch:
    types: trigger-ga___beam_PreCommit_Website_Stage_GCS.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
