concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_LoadTests_Go_GBK_Dataflow_Batch:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Go GBK Dataflow Batch''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/go_GBK_Dataflow_Batch_10b.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/go_GBK_Dataflow_Batch_100b.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/go_GBK_Dataflow_Batch_100kb.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/go_GBK_Dataflow_Batch_Fanout_4.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/go_GBK_Dataflow_Batch_Fanout_8.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/go_GBK_Dataflow_Batch_Reiteration_10KB.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/go_GBK_Dataflow_Batch_Reiteration_2MB.txt

          '
        test-language: go
        test-type: load
    - continue-on-error: true
      name: get current time
      run: echo "NOW_UTC=$(date '+%m%d%H%M%S' --utc)" >> $GITHUB_ENV
    - continue-on-error: true
      name: run GBK Dataflow Batch Go Load Test 1 (10 b records)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=group_by_key \

          -Prunner=DataflowRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Go_GBK_Dataflow_Batch_test_arguments_1
          }} --job_name=load-tests-go-dataflow-batch-gbk-1-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:go:test:load:run
    - continue-on-error: true
      name: run GBK Dataflow Batch Go Load Test 2 (100 b records)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=group_by_key \

          -Prunner=DataflowRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Go_GBK_Dataflow_Batch_test_arguments_2
          }} --job_name=load-tests-go-dataflow-batch-gbk-2-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:go:test:load:run
    - continue-on-error: true
      name: run GBK Dataflow Batch Go Load Test 3 (100 kb records)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=group_by_key \

          -Prunner=DataflowRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Go_GBK_Dataflow_Batch_test_arguments_3
          }} --job_name=load-tests-go-dataflow-batch-gbk-3-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:go:test:load:run
    - continue-on-error: true
      name: run GBK Dataflow Batch Go Load Test 4 (fanout 4)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=group_by_key \

          -Prunner=DataflowRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Go_GBK_Dataflow_Batch_test_arguments_4
          }} --job_name=load-tests-go-dataflow-batch-gbk-4-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:go:test:load:run
    - continue-on-error: true
      name: run GBK Dataflow Batch Go Load Test 5 (fanout 8)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=group_by_key \

          -Prunner=DataflowRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Go_GBK_Dataflow_Batch_test_arguments_5
          }} --job_name=load-tests-go-dataflow-batch-gbk-5-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:go:test:load:run
    - continue-on-error: true
      name: run GBK Dataflow Batch Go Load Test 6 (reiterate 4 times 10 kb)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=group_by_key \

          -Prunner=DataflowRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Go_GBK_Dataflow_Batch_test_arguments_6
          }} --job_name=load-tests-go-dataflow-batch-gbk-6-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:go:test:load:run
    - continue-on-error: true
      name: run GBK Dataflow Batch Go Load Test 7 (reiterate 4 times 2 mb)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=group_by_key \

          -Prunner=DataflowRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Go_GBK_Dataflow_Batch_test_arguments_7
          }} --job_name=load-tests-go-dataflow-batch-gbk-7-${{env.NOW_UTC}}'''
        gradle-command: :sdks:go:test:load:run
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Go_GBK_Dataflow_Batch
        job_phrase:
        - Run Load Tests Go GBK Dataflow Batch
    timeout-minutes: 720
name: LoadTests Go GBK Dataflow Batch
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Go_GBK_Dataflow_Batch.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
