concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_PerformanceTests_Kafka_IO:
    env:
      KAFKA_SERVICE_PORT: 32400
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Java KafkaIO Performance Test''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      id: auth
      name: Authenticate on GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - continue-on-error: true
      name: Set k8s access
      uses: ./.github/actions/setup-k8s-access
      with:
        cluster_name: io-datastores
        k8s_namespace: ${{ matrix.job_name }}-${{ github.run_id }}
    - continue-on-error: true
      id: install_kafka
      name: Install Kafka
      run: 'cd ${{ github.workspace }}/.test-infra/kubernetes/kafka-cluster/

        kubectl apply -R -f ${{ github.workspace }}/.test-infra/kubernetes/kafka-cluster/

        '
    - continue-on-error: true
      id: set_brokers
      name: Set up Kafka brokers
      run: "declare -a kafka_service_brokers\nfor INDEX in {0..2}; do\n  kubectl wait\
        \ svc/outside-${INDEX} --for=jsonpath='{.status.loadBalancer.ingress[0].ip}'\
        \ --timeout=120s\n  kafka_service_brokers[$INDEX]=$(kubectl get svc outside-${INDEX}\
        \ -o jsonpath='{.status.loadBalancer.ingress[0].ip}')\n  echo \"KAFKA_SERVICE_BROKER_${INDEX}=${kafka_service_brokers[$INDEX]}\"\
        \ >> $GITHUB_OUTPUT\ndone\n"
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/performance-tests-pipeline-options/kafka_IO_Streaming.txt

          ${{ github.workspace }}/.github/workflows/performance-tests-pipeline-options/kafka_IO_Batch.txt

          '
        arguments: '--kafkaBootstrapServerAddresses=${{ steps.set_brokers.outputs.KAFKA_SERVICE_BROKER_0
          }}:${{ env.KAFKA_SERVICE_PORT }},${{ steps.set_brokers.outputs.KAFKA_SERVICE_BROKER_1
          }}:${{ env.KAFKA_SERVICE_PORT }},${{ steps.set_brokers.outputs.KAFKA_SERVICE_BROKER_2
          }}:${{ env.KAFKA_SERVICE_PORT }}

          '
        test-language: java
        test-type: performance
    - continue-on-error: true
      name: Run Java KafkaIO Performance Streaming Test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--tests org.apache.beam.sdk.io.kafka.KafkaIOIT.testKafkaIOReadsAndWritesCorrectlyInStreaming
          \

          --info \

          -DintegrationTestRunner=dataflow \

          -DintegrationTestPipelineOptions=''[${{env.beam_PerformanceTests_Kafka_IO_test_arguments_1}}]''
          \

          '
        gradle-command: :sdks:java:io:kafka:integrationTest
    - continue-on-error: true
      name: Run Java KafkaIO Performance Batch Test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--tests org.apache.beam.sdk.io.kafka.KafkaIOIT.testKafkaIOReadsAndWritesCorrectlyInBatch
          \

          --info \

          -DintegrationTestRunner=dataflow \

          -DintegrationTestPipelineOptions=''[${{env.beam_PerformanceTests_Kafka_IO_test_arguments_2}}]'''
        gradle-command: :sdks:java:io:kafka:integrationTest
    strategy:
      matrix:
        job_name:
        - beam_PerformanceTests_Kafka_IO
        job_phrase:
        - Run Java KafkaIO Performance Test
    timeout-minutes: 120
name: PerformanceTests Kafka IO
on:
  repository_dispatch:
    types: trigger-ga___beam_PerformanceTests_Kafka_IO.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
