concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Java 11 GBK Dataflow V2 Batch''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: 11
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_GBK_Dataflow_V2_Batch_Java11_2GB_of_10B_records.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_GBK_Dataflow_V2_Batch_Java11_2GB_of_100B_records.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_GBK_Dataflow_V2_Batch_Java11_2GB_of_100kB_records.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_GBK_Dataflow_V2_Batch_Java11_fanout_4_times_with_2GB_10-byte_records_total.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_GBK_Dataflow_V2_Batch_Java11_fanout_8_times_with_2GB_10-byte_records_total.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_GBK_Dataflow_V2_Batch_Java11_reiterate_4_times_10kB_values.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_GBK_Dataflow_V2_Batch_Java11_reiterate_4_times_2MB_values.txt

          '
        test-language: java
        test-type: load
    - continue-on-error: true
      name: run Load test 2GB of 10B records
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.GroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=11 \

          -Pjava11Home=$JAVA_HOME_11_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11_test_arguments_1
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run Load test 2GB of 100B records
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.GroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=11 \

          -Pjava11Home=$JAVA_HOME_11_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11_test_arguments_2
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run Load test 2GB of 100kB records
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.GroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=11 \

          -Pjava11Home=$JAVA_HOME_11_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11_test_arguments_3
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run Load test fanout 4 times with 2GB 10-byte records total
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.GroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=11 \

          -Pjava11Home=$JAVA_HOME_11_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11_test_arguments_4
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run Load test fanout 8 times with 2GB 10-byte records total
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.GroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=11 \

          -Pjava11Home=$JAVA_HOME_11_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11_test_arguments_5
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run Load test reiterate 4 times 10kB values
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.GroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=11 \

          -Pjava11Home=$JAVA_HOME_11_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11_test_arguments_6
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run Load test reiterate 4 times 2MB values
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.GroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=11 \

          -Pjava11Home=$JAVA_HOME_11_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11_test_arguments_7
          }}'''
        gradle-command: :sdks:java:testing:load-tests:run
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11
        job_phrase:
        - Run Load Tests Java 11 GBK Dataflow V2 Batch
    timeout-minutes: 240
name: LoadTests Java GBK Dataflow V2 Batch Java11
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Java_GBK_Dataflow_V2_Batch_Java11.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
