concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_CleanUpGCPResources:
    if: '(github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event_name == ''workflow_dispatch'' ||

      github.event.comment.body == ''Run Clean GCP Resources''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        disable-cache: true
    - continue-on-error: true
      id: auth
      name: Authenticate on GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - continue-on-error: true
      name: Install gcloud bigtable cli
      run: gcloud components install cbt
    - continue-on-error: true
      name: run cleanup GCP resources
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        gradle-command: :beam-test-tools:cleanupOtherStaleResources
    strategy:
      matrix:
        job_name:
        - beam_CleanUpGCPResources
        job_phrase:
        - Run Clean GCP Resources
    timeout-minutes: 100
name: Clean Up GCP Resources
on:
  repository_dispatch:
    types: trigger-ga___beam_CleanUpGCPResources.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
