concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_Java_Examples_Dataflow_V2_Java:
    if: "github.event_name == 'workflow_dispatch' ||\ngithub.event_name == 'pull_request_target'\
      \ ||\n(github.event_name == 'schedule' && github.repository == 'apache/beam')\
      \ ||\n(contains(github.event.comment.body, 'Run Java') &&\n   contains(github.event.comment.body,\
      \ 'Examples on Dataflow Runner V2'))\n"
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.java_version
      }} ${{ matrix.job_phrase_2 }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase_1 }} ${{ matrix.java_version }} ${{
          matrix.job_phrase_2 }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.java_version
          }} ${{ matrix.job_phrase_2 }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: '${{ matrix.java_version }}

          8

          '
    - continue-on-error: true
      name: run PostCommit Java Examples Dataflow V2 Java${{ matrix.java_version }}
        script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PdisableSpotlessCheck=true \

          -PdisableCheckStyle=true \

          -PskipCheckerFramework \

          -PtestJavaVersion=${{ matrix.java_version }} \

          -Pjava${{ matrix.java_version }}Home=$JAVA_HOME_${{ matrix.java_version
          }}_X64 \

          '
        gradle-command: :runners:google-cloud-dataflow-java:examplesJavaRunnerV2IntegrationTest
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/build/test-results/**/*.xml'
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '11'
        - '17'
        - '21'
        job_name:
        - beam_PostCommit_Java_Examples_Dataflow_V2_Java
        job_phrase_1:
        - Run Java
        job_phrase_2:
        - Examples on Dataflow Runner V2
    timeout-minutes: 180
name: PostCommit Java Examples Dataflow V2 Java
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Java_Examples_Dataflow_V2_Java.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
