concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_Java_LoadTests_Combine_Smoke:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Java Load Tests Combine Smoke''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_LoadTests_Combine_Smoke_CombineLoadTest_load_test_Dataflow-1.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_LoadTests_Combine_Smoke_CombineLoadTest_load_test_Dataflow-2.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_LoadTests_Combine_Smoke_CombineLoadTest_load_test_Dataflow-3.txt

          '
        test-language: java
        test-type: load
    - continue-on-error: true
      name: run CombineLoadTest load test Dataflow-1
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.CombineLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          ''-PloadTest.args=${{ env.beam_Java_LoadTests_Combine_Smoke_test_arguments_1
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run CombineLoadTest load test Dataflow-2
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.CombineLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          ''-PloadTest.args=${{ env.beam_Java_LoadTests_Combine_Smoke_test_arguments_2
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run CombineLoadTest load test Dataflow-3
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.CombineLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          ''-PloadTest.args=${{ env.beam_Java_LoadTests_Combine_Smoke_test_arguments_3
          }}'''
        gradle-command: :sdks:java:testing:load-tests:run
    strategy:
      matrix:
        job_name:
        - beam_Java_LoadTests_Combine_Smoke
        job_phrase:
        - Run Java Load Tests Combine Smoke
    timeout-minutes: 720
name: LoadTests Java Combine Smoke
on:
  repository_dispatch:
    types: trigger-ga___beam_Java_LoadTests_Combine_Smoke.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
