concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_PerformanceTests_BigQueryIO_Batch_Java_Json:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run BigQueryIO Batch Performance Test Java Json''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/performance-tests-pipeline-options/bigQueryIO_Batch_Java_Json.txt

          '
        arguments: '--testBigQueryTable=bqio_write_10GB_java_json_$(date ''+%m%d%H%M%S''
          --utc)

          '
        test-language: java
        test-type: performance
    - continue-on-error: true
      name: run Java BigQueryIO Batch Json Performance Test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--tests org.apache.beam.sdk.bigqueryioperftests.BigQueryIOIT \

          --info \

          -DintegrationTestRunner=dataflow \

          -DintegrationTestPipelineOptions=''[${{ env.beam_PerformanceTests_BigQueryIO_Batch_Java_Json_test_arguments_1
          }}]'' \

          '
        gradle-command: :sdks:java:io:bigquery-io-perf-tests:integrationTest
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/build/test-results/**/*.xml'
    strategy:
      matrix:
        job_name:
        - beam_PerformanceTests_BigQueryIO_Batch_Java_Json
        job_phrase:
        - Run BigQueryIO Batch Performance Test Java Json
    timeout-minutes: 100
name: PerformanceTests BigQueryIO Batch Java Json
on:
  repository_dispatch:
    types: trigger-ga___beam_PerformanceTests_BigQueryIO_Batch_Java_Json.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
