concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_Java_Examples__Dataflow_ARM:
    if: 'github.event_name == ''push'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      startswith(github.event.comment.body, ''Run Java_Examples_Dataflow_ARM PostCommit'')

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.java_version
      }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }} ${{ matrix.java_version }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.java_version
          }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: GCloud Docker credential helper
      run: 'gcloud auth configure-docker us.gcr.io

        '
    - continue-on-error: true
      id: set_tag
      name: Generate TAG unique variable based on timestamp
      run: echo "TAG=$(date +'%Y%m%d-%H%M%S%N')" >> $GITHUB_OUTPUT
    - continue-on-error: true
      name: run javaExamplesDataflowARMPostCommit script for Java${{ matrix.java_version
        }}
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PtestJavaVersion=${{ matrix.java_version }} \

          -Pjava${{ matrix.java_version }}Home=$JAVA_HOME_${{ matrix.java_version
          }}_X64 \

          -Pcontainer-architecture-list=arm64,amd64 \

          -Ppush-containers \

          -Pdocker-repository-root=us.gcr.io/apache-beam-testing/github-actions \

          -Pdocker-tag=${{ steps.set_tag.outputs.TAG }} \

          -PdisableSpotlessCheck=true \

          -PdisableCheckStyle=true \

          -PskipCheckerFramework \

          '
        gradle-command: :runners:google-cloud-dataflow-java:arm:examplesJavaRunnerV2IntegrationTestARM
        max-workers: 12
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/build/test-results/**/*.xml'
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '8'
        - '11'
        - '17'
        - '21'
        job_name:
        - beam_PostCommit_Java_Examples__Dataflow_ARM
        job_phrase:
        - Run Java_Examples_Dataflow_ARM PostCommit
    timeout-minutes: 120
name: PostCommit Java Examples Dataflow ARM
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Java_Examples_Dataflow_ARM.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
