concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_LoadTests_Java_CoGBK_Dataflow_Streaming:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Java CoGBK Dataflow Streaming''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_CoGBK_Dataflow_Streaming_2GB_SingleKey.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_CoGBK_Dataflow_Streaming_2GB_MultipleKey.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_CoGBK_Dataflow_Streaming_2GB_Reiteration_10KB.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_CoGBK_Dataflow_Streaming_2GB_Reiteration_2MB.txt

          '
        test-language: java
        test-type: load
    - continue-on-error: true
      name: run CoGBK Dataflow Streaming Java Load Test 1 (single key)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.CoGroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_CoGBK_Dataflow_Streaming_test_arguments_1
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run CoGBK Dataflow Streaming Java Load Test 2 (multiple key)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.CoGroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_CoGBK_Dataflow_Streaming_test_arguments_2
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run CoGBK Dataflow Streaming Java Load Test 3 (reiteration 10KB value)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.CoGroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_CoGBK_Dataflow_Streaming_test_arguments_3
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run CoGBK Dataflow Streaming Java Load Test 4 (reiteration 2MB value)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.CoGroupByKeyLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_CoGBK_Dataflow_Streaming_test_arguments_4
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: '**/build/test-results/**/*.xml'
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Java_CoGBK_Dataflow_Streaming
        job_phrase:
        - Run Load Tests Java CoGBK Dataflow Streaming
    timeout-minutes: 240
name: LoadTests Java CoGBK Dataflow Streaming
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Java_CoGBK_Dataflow_Streaming.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
