concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.body || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_JavaVersions:
    if: "github.event_name == 'workflow_dispatch' ||\n(github.event_name == 'schedule'\
      \ && github.repository == 'apache/beam') ||\n(contains(github.event.comment.body,\
      \ 'Run Load Tests Java') &&\n   contains(github.event.comment.body, 'ParDo Dataflow\
      \ V2 Streaming'))\n"
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.java_version
      }} ${{ matrix.job_phrase_2 }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase_1 }} ${{ matrix.java_version }} ${{
          matrix.job_phrase_2 }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase_1 }} ${{ matrix.java_version
          }} ${{ matrix.job_phrase_2 }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_Dataflow_V2_Streaming_JavaVersions_10_times.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_Dataflow_V2_Streaming_JavaVersions_200_times.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_Dataflow_V2_Streaming_JavaVersions_10_counters.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_Dataflow_V2_Streaming_JavaVersions_100_counters.txt

          '
        arguments: '--influxTags={\"runnerVersion\":\"v2\",\"jdk\":\"java${{ matrix.java_version
          }}\"}

          '
        test-language: java
        test-type: load
    - continue-on-error: true
      name: run ParDo Dataflow V2 Streaming Java Load Test 1 (10 times)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=${{ matrix.java_version }} \

          -Pjava${{ matrix.java_version }}Home=$JAVA_HOME_${{ matrix.java_version
          }}_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_JavaVersions_test_arguments_1
          }} --appName=load_tests_Java${{ matrix.java_version }}_Dataflow_V2_streaming_ParDo_1''
          \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run ParDo Dataflow V2 Streaming Java Load Test 2 (200 times)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=${{ matrix.java_version }} \

          -Pjava${{ matrix.java_version }}Home=$JAVA_HOME_${{ matrix.java_version
          }}_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_JavaVersions_test_arguments_2
          }} --appName=load_tests_Java${{ matrix.java_version }}_Dataflow_V2_streaming_ParDo_2''
          \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run ParDo Dataflow V2 Streaming Java Load Test 3 (10 counters)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=${{ matrix.java_version }} \

          -Pjava${{ matrix.java_version }}Home=$JAVA_HOME_${{ matrix.java_version
          }}_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_JavaVersions_test_arguments_3
          }} --appName=load_tests_Java${{ matrix.java_version }}_Dataflow_V2_streaming_ParDo_3''
          \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run ParDo Dataflow V2 Streaming Java Load Test 4 (100 counters)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:google-cloud-dataflow-java \

          -Prunner.version=V2 \

          -PtestJavaVersion=${{ matrix.java_version }} \

          -Pjava${{ matrix.java_version }}Home=$JAVA_HOME_${{ matrix.java_version
          }}_X64 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_JavaVersions_test_arguments_4
          }} --appName=load_tests_Java${{ matrix.java_version }}_Dataflow_V2_streaming_ParDo_4'''
        gradle-command: :sdks:java:testing:load-tests:run
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '11'
        - '17'
        job_name:
        - beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_JavaVersions
        job_phrase_1:
        - Run Load Tests Java
        job_phrase_2:
        - ParDo Dataflow V2 Streaming
    timeout-minutes: 720
name: LoadTests Java ParDo Dataflow V2 Streaming JavaVersions
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_JavaVersions.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
