env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostRelease_NightlySnapshot:
    name: beam_PostRelease_NightlySnapshot
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: default
    - continue-on-error: true
      name: run PostRelease validation script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-Pver=''${{ github.event.inputs.RELEASE }}'' \

          -Prepourl=''${{ github.event.inputs.SNAPSHOT_URL }}'' \

          '
        gradle-command: :release:runJavaExamplesValidationTask
name: PostRelease Nightly Snapshot
on:
  repository_dispatch:
    types: trigger-ga___beam_PostRelease_NightlySnapshot.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
