concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PreCommit_Python_PVR_Flink:
    if: 'github.event_name == ''push'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event_name == ''workflow_dispatch'' ||

      github.event.comment.body == ''Run Python_PVR_Flink PreCommit''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: 3.12
    - continue-on-error: true
      env:
        CLOUDSDK_CONFIG: ${{ env.KUBELET_GCLOUD_CONFIG_PATH}}
      name: run Python PVR Flink PreCommit script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PpythonVersion=3.12 \

          '
        gradle-command: :sdks:python:test-suites:portable:py312:flinkValidatesRunner
    - continue-on-error: true
      if: failure()
      name: Archive Python Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Python Test Results
        path: '**/pytest*.xml'
    - continue-on-error: true
      if: always()
      name: Publish Python Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/pytest*.xml'
    strategy:
      matrix:
        job_name:
        - beam_PreCommit_Python_PVR_Flink
        job_phrase:
        - Run Python_PVR_Flink PreCommit
    timeout-minutes: 120
name: PreCommit Python PVR Flink
on:
  repository_dispatch:
    types: trigger-ga___beam_PreCommit_Python_PVR_Flink.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
