concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  ARTIFACTS_DIR: gs://beam-flink-cluster/beam-loadtests-python-cogbk-flink-batch-${{
    github.run_id }}
  CLUSTER_NAME: beam-loadtests-python-cogbk-flink-batch-${{ github.run_id }}
  DETACHED_MODE: true
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  FLINK_DOWNLOAD_URL: https://archive.apache.org/dist/flink/flink-1.15.0/flink-1.15.0-bin-scala_2.12.tgz
  FLINK_TASKMANAGER_SLOTS: 1
  GCLOUD_ZONE: us-central1-a
  GCS_BUCKET: gs://beam-flink-cluster
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  HADOOP_DOWNLOAD_URL: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
  HARNESS_IMAGES_TO_PULL: gcr.io/apache-beam-testing/beam-sdk/beam_go_sdk:latest
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
  JOB_SERVER_IMAGE: gcr.io/apache-beam-testing/beam_portability/beam_flink1.15_job_server:latest
jobs:
  beam_LoadTests_Python_CoGBK_Flink_Batch:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Python CoGBK Flink Batch''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: default
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_CoGBK_Dataflow_Flink_Batch_100b_Single_Key.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_CoGBK_Dataflow_Flink_Batch_100b_Multiple_Keys.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_CoGBK_Dataflow_Flink_Batch_10kB.txt

          '
        test-language: python
        test-type: load
    - continue-on-error: true
      env:
        FLINK_NUM_WORKERS: 5
      name: Start Flink with parallelism 5
      run: 'cd ${{ github.workspace }}/.test-infra/dataproc; ./flink_cluster.sh create

        '
    - continue-on-error: true
      id: datetime
      name: Set current datetime
      run: 'echo "datetime=$(date ''+%m%d%H%M%S'' --utc)" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: run CoGBK 2GB of 100B records with a single key
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--info \

          -PloadTest.mainClass=apache_beam.testing.load_tests.co_group_by_key_test
          \

          -Prunner=FlinkRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_CoGBK_Flink_Batch_test_arguments_1
          }} --job_name=load-tests-python-flink-batch-cogbk-1-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run CoGBK 2GB of 100B records with multiple keys
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--info \

          -PloadTest.mainClass=apache_beam.testing.load_tests.co_group_by_key_test
          \

          -Prunner=FlinkRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_CoGBK_Flink_Batch_test_arguments_2
          }} --job_name=load-tests-python-flink-batch-cogbk-2-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run CoGBK reiterate 4 times 10kB values
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--info \

          -PloadTest.mainClass=apache_beam.testing.load_tests.co_group_by_key_test
          \

          -Prunner=FlinkRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_CoGBK_Flink_Batch_test_arguments_2
          }} --job_name=load-tests-python-flink-batch-cogbk-3-${{ steps.datetime.outputs.datetime
          }}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      if: always()
      name: Teardown Flink
      run: ${{ github.workspace }}/.test-infra/dataproc/flink_cluster.sh delete
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Python_CoGBK_Flink_Batch
        job_phrase:
        - Run Load Tests Python CoGBK Flink Batch
    timeout-minutes: 720
name: LoadTests Python CoGBK Flink Batch
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Python_CoGBK_Flink_Batch.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
