concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PostCommit_Java_ValidatesRunner_Direct_JavaVersions:
    if: 'github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      startswith(github.event.comment.body, ''Run Direct ValidatesRunner Java'')

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.java_version
      }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }} ${{ matrix.java_version }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }}) ${{ matrix.java_version
          }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: '${{ matrix.java_version }}

          8

          '
    - continue-on-error: true
      name: run jar Java${{ matrix.java_version }} script
      run: './gradlew :runners:direct-java:shadowJar :runners:direct-java:shadowTestJar
        \

        -Dorg.gradle.java.home=$JAVA_HOME_8_X64

        '
    - continue-on-error: true
      name: run validatesRunner Java${{ matrix.java_version }} script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-x shadowJar \

          -x shadowTestJar \

          -x compileJava \

          -x compileTestJava \

          -Dorg.gradle.java.home=$JAVA_HOME_${{ matrix.java_version }}_X64 \

          '
        gradle-command: :runners:direct-java:validatesRunner
    - continue-on-error: true
      if: ${{ !success() }}
      name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: '**/build/reports/tests/'
    - continue-on-error: true
      if: always()
      name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off'
          }}
        commit: ${{ env.prsha || env.GITHUB_SHA }}
        files: '**/build/test-results/**/*.xml'
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '11'
        - '17'
        job_name:
        - beam_PostCommit_Java_ValidatesRunner_Direct_JavaVersions
        job_phrase:
        - Run Direct ValidatesRunner Java
    timeout-minutes: 480
name: PostCommit Java ValidatesRunner Direct JavaVersions
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Java_ValidatesRunner_Direct_JavaVersions.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
