concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_Publish_Website:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')

      '
    name: beam_Publish_Website
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        disable-cache: true
    - continue-on-error: true
      name: run PostCommit Website Publish script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: -PgitPublishRemote="https://github.com/apache/beam.git"
        gradle-command: :website:clean :website:publishWebsite
    - continue-on-error: true
      uses: actions/checkout@v4
    timeout-minutes: 30
name: Publish Website
on:
  repository_dispatch:
    types: trigger-ga___beam_Publish_Website.yml
permissions:
  actions: write
  checks: read
  contents: write
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
