concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  beam_PreCommit_PythonDocker:
    if: 'github.event_name == ''push'' ||

      github.event_name == ''pull_request_target'' ||

      github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      startsWith(github.event.comment.body, ''Run PythonDocker PreCommit'')

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.python_version
      }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }} ${{ matrix.python_version }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.python_version
          }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        go-version: default
        java-version: default
        python-version: ${{ matrix.python_version }}
    - continue-on-error: true
      name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
        install: true
    - continue-on-error: true
      id: set_py_ver_clean
      name: Set PY_VER_CLEAN
      run: 'PY_VER=${{ matrix.python_version }}

        PY_VER_CLEAN=${PY_VER//.}

        echo "py_ver_clean=$PY_VER_CLEAN" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Run pythonDockerBuildPreCommit
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-Pposargs=apache_beam/dataframe/ \

          -PpythonVersion=${{ matrix.python_version }}

          '
        gradle-command: :sdks:python:container:py${{steps.set_py_ver_clean.outputs.py_ver_clean}}:docker
    strategy:
      fail-fast: false
      matrix:
        job_name:
        - beam_PreCommit_PythonDocker
        job_phrase:
        - Run PythonDocker PreCommit
        python_version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    timeout-minutes: 30
name: PreCommit Python Docker
on:
  repository_dispatch:
    types: trigger-ga___beam_PreCommit_PythonDocker.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
