concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_COMMAND_ARGUMENTS: '--dataSize=1GB

    --sourceType=PARQUET

    --dataDirectory=gs://beam-tpcds/datasets/parquet/nonpartitioned

    --resultsDirectory=gs://beam-tpcds/results/spark3-rdd/

    --tpcParallel=1

    '
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
  tpcdsBigQueryArgs: "--bigQueryTable=tpcds \n--bigQueryDataset=tpcds \n--project=apache-beam-testing\
    \ \n--resourceNameMode=QUERY_RUNNER_AND_MODE \n--exportSummaryToBigQuery=true\
    \ \n--tempLocation=gs://temp-storage-for-perf-tests/tpcds \n"
  tpcdsInfluxDBArgs: "--influxDatabase=beam_test_metrics \n--influxHost=http://10.128.0.96:8086\
    \ \n--baseInfluxMeasurement=tpcds \n--exportSummaryToInfluxDB=true \n--influxRetentionPolicy=forever\
    \ \n"
  tpcdsQueriesArg: 3,7,10,25,26,29,35,38,40,42,43,52,55,69,79,83,84,87,93,96
jobs:
  beam_PostCommit_Java_Tpcds_Spark:
    if: 'github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Spark Runner Tpcds Tests''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }}) ${{ matrix.runner }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }}) ${{ matrix.runner
          }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: run PostCommit Java Tpcds Spark (${{ matrix.runner }}) script
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-Ptpcds.runner=:runners:spark:3 \

          "-Ptpcds.args=${{env.tpcdsBigQueryArgs}} ${{env.tpcdsInfluxDBArgs}} ${{
          env.GRADLE_COMMAND_ARGUMENTS }} --runner=${{ matrix.runner }} --queries=${{env.tpcdsQueriesArg}}"
          \

          '
        gradle-command: :sdks:java:testing:tpcds:run
    strategy:
      matrix:
        job_name:
        - beam_PostCommit_Java_Tpcds_Spark
        job_phrase:
        - Run Spark Runner Tpcds Tests
        runner:
        - SparkRunner
        - SparkStructuredStreamingRunner
    timeout-minutes: 240
name: PostCommit Java Tpcds Spark
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Java_Tpcds_Spark.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
