concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_LoadTests_Java_ParDo_SparkStructuredStreaming_Batch:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Java ParDo SparkStructuredStreaming
      Batch''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_SparkStructuredStreaming_Batch_10_times.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_SparkStructuredStreaming_Batch_200_times.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_SparkStructuredStreaming_Batch_10_counters.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/java_ParDo_SparkStructuredStreaming_Batch_100_counters.txt

          '
        test-language: java
        test-type: load
    - continue-on-error: true
      name: run ParDo SparkStructuredStreaming Batch Java Load Test 1 (10 times)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:spark:3 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_SparkStructuredStreaming_Batch_test_arguments_1
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run ParDo SparkStructuredStreaming Batch Java Load Test 2 (200 times)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:spark:3 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_SparkStructuredStreaming_Batch_test_arguments_2
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run ParDo SparkStructuredStreaming Batch Java Load Test 3 (10 counters)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:spark:3 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_SparkStructuredStreaming_Batch_test_arguments_3
          }}'' \

          '
        gradle-command: :sdks:java:testing:load-tests:run
    - continue-on-error: true
      name: run ParDo SparkStructuredStreaming Batch Java Load Test 4 (100 counters)
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=org.apache.beam.sdk.loadtests.ParDoLoadTest
          \

          -Prunner=:runners:spark:3 \

          ''-PloadTest.args=${{ env.beam_LoadTests_Java_ParDo_SparkStructuredStreaming_Batch_test_arguments_4
          }}'''
        gradle-command: :sdks:java:testing:load-tests:run
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Java_ParDo_SparkStructuredStreaming_Batch
        job_phrase:
        - Run Load Tests Java ParDo SparkStructuredStreaming Batch
    timeout-minutes: 720
name: LoadTests Java ParDo SparkStructuredStreaming Batch
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Java_ParDo_SparkStructuredStreaming_Batch.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
