concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  ARTIFACTS_DIR: gs://beam-flink-cluster/beam-loadtests-py-gbk-flk-batch-${{ github.run_id
    }}
  CLUSTER_NAME: beam-loadtests-py-gbk-flk-batch-${{ github.run_id }}
  DETACHED_MODE: true
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  FLINK_DOWNLOAD_URL: https://archive.apache.org/dist/flink/flink-1.15.0/flink-1.15.0-bin-scala_2.12.tgz
  FLINK_TASKMANAGER_SLOTS: 1
  GCLOUD_ZONE: us-central1-a
  GCS_BUCKET: gs://beam-flink-cluster
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  HADOOP_DOWNLOAD_URL: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
  HARNESS_IMAGES_TO_PULL: gcr.io/apache-beam-testing/beam-sdk/beam_go_sdk:latest
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
  JOB_SERVER_IMAGE: gcr.io/apache-beam-testing/beam_portability/beam_flink1.15_job_server:latest
jobs:
  beam_LoadTests_Python_GBK_Flink_Batch:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Load Tests Python GBK Flink Batch''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: default
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_GBK_Flink_Batch_2GB_of_10B_records.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_GBK_Flink_Batch_2GB_of_100B_records.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_GBK_Flink_Batch_fanout_4_times_with_2GB_10-byte_records_total.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_GBK_Flink_Batch_fanout_8_times_with_2GB_10-byte_records_total.txt

          ${{ github.workspace }}/.github/workflows/load-tests-pipeline-options/python_GBK_Flink_Batch_reiterate_4_times_10kB_values.txt

          '
        test-language: python
        test-type: load
    - continue-on-error: true
      name: get current time
      run: echo "NOW_UTC=$(date '+%m%d%H%M%S' --utc)" >> $GITHUB_ENV
    - continue-on-error: true
      env:
        FLINK_NUM_WORKERS: 5
      name: Start Flink with parallelism 5
      run: 'cd ${{ github.workspace }}/.test-infra/dataproc; ./flink_cluster.sh create

        '
    - continue-on-error: true
      name: run Flink Batch 2GB of 10B records test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.group_by_key_test
          \

          -Prunner=PortableRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_GBK_Flink_Batch_test_arguments_1
          }} --job_name=load-tests-python-flink-batch-gbk-1-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run --info
    - continue-on-error: true
      name: run Flink Batch 2GB of 100B records test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.group_by_key_test
          \

          -Prunner=PortableRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_GBK_Flink_Batch_test_arguments_2
          }} --job_name=load-tests-python-flink-batch-gbk-2-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run reiterate 4 times 10kB values test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.group_by_key_test
          \

          -Prunner=PortableRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_GBK_Flink_Batch_test_arguments_5
          }} --job_name=load-tests-python-flink-batch-gbk-6-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      env:
        FLINK_NUM_WORKERS: 16
      name: Restart Flink with parallelism 16
      run: 'cd ${{ github.workspace }}/.test-infra/dataproc; ./flink_cluster.sh restart

        '
    - continue-on-error: true
      name: run fanout 4 times with 2GB 10-byte records total test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.group_by_key_test
          \

          -Prunner=PortableRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_GBK_Flink_Batch_test_arguments_3
          }} --job_name=load-tests-python-flink-batch-gbk-4-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      name: run fanout 8 times with 2GB 10-byte records total test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PloadTest.mainClass=apache_beam.testing.load_tests.group_by_key_test
          \

          -Prunner=PortableRunner \

          ''-PloadTest.args=${{ env.beam_LoadTests_Python_GBK_Flink_Batch_test_arguments_4
          }} --job_name=load-tests-python-flink-batch-gbk-5-${{env.NOW_UTC}}'' \

          '
        gradle-command: :sdks:python:apache_beam:testing:load_tests:run
    - continue-on-error: true
      if: always()
      name: Teardown Flink
      run: '${{ github.workspace }}/.test-infra/dataproc/flink_cluster.sh delete

        '
    strategy:
      matrix:
        job_name:
        - beam_LoadTests_Python_GBK_Flink_Batch
        job_phrase:
        - Run Load Tests Python GBK Flink Batch
    timeout-minutes: 720
name: LoadTests Python GBK Flink Batch
on:
  repository_dispatch:
    types: trigger-ga___beam_LoadTests_Python_GBK_Flink_Batch.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
