concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
  INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
jobs:
  beam_PerformanceTests_AvroIOIT:
    if: 'github.event_name == ''workflow_dispatch'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Java AvroIO Performance Test''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
    - continue-on-error: true
      name: Prepare test arguments
      uses: ./.github/actions/test-arguments-action
      with:
        argument-file-paths: '${{ github.workspace }}/.github/workflows/performance-tests-pipeline-options/avroIOIT.txt

          '
        arguments: '--filenamePrefix=gs://temp-storage-for-perf-tests/${{ matrix.job_name
          }}/${{github.run_id}}/

          '
        test-language: java
        test-type: performance
    - continue-on-error: true
      name: run integrationTest
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '--tests org.apache.beam.sdk.io.avro.AvroIOIT \

          --info \

          -Dfilesystem=gcs \

          -DintegrationTestRunner=dataflow \

          -DintegrationTestPipelineOptions=''[${{ env.beam_PerformanceTests_AvroIOIT_test_arguments_1
          }}]'' \

          '
        gradle-command: :sdks:java:io:file-based-io-tests:integrationTest
    strategy:
      matrix:
        job_name:
        - beam_PerformanceTests_AvroIOIT
        job_phrase:
        - Run Java AvroIO Performance Test
    timeout-minutes: 100
name: PerformanceTests AvroIOIT
on:
  repository_dispatch:
    types: trigger-ga___beam_PerformanceTests_AvroIOIT.yml
permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: write
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read
