concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref
    || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login
    }}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  GRADLE_JAVA_COMMAND_ARGUMENTS: '--manageResources=false

    --monitorJobs=true

    --bigQueryTable=nexmark

    --bigQueryDataset=nexmark

    --project=apache-beam-testing

    --resourceNameMode=QUERY_RUNNER_AND_MODE

    --exportSummaryToBigQuery=true

    --tempLocation=gs://temp-storage-for-perf-tests/nexmark

    --influxDatabase=beam_test_metrics

    --influxHost=http://10.128.0.96:8086

    --baseInfluxMeasurement=nexmark

    --exportSummaryToInfluxDB=true

    --influxRetentionPolicy=forever

    --suite=SMOKE

    --enforceEncodability=true

    --enforceImmutability=true

    --runner=DirectRunner

    --numEvents=100000

    '
  GRADLE_PYTHON_COMMAND_ARGUMENTS: '--monitor_jobs

    --big_query_table=nexmark

    --big_query_dataset=nexmark

    --project=apache-beam-testing

    --resource_name_mode=QUERY_RUNNER_AND_MODE

    --export_summary_to_big_query

    --temp_location=gs://temp-storage-for-perf-tests/nexmark

    --influx_database=beam_test_metrics

    --influx_host=http://10.128.0.96:8086

    --base_influx_measurement=nexmark

    --export_summary_to_influx_db

    --influx_retention_policy=forever

    --suite=SMOKE

    --enforce_encodability

    --enforce_immutability

    --runner=DirectRunner

    --num_events=100000

    '
jobs:
  beam_PostCommit_Python_Nexmark_Direct:
    if: 'github.event_name == ''workflow_dispatch'' ||

      github.event_name == ''pull_request_target'' ||

      (github.event_name == ''schedule'' && github.repository == ''apache/beam'')
      ||

      github.event.comment.body == ''Run Python Direct Runner Nexmark Tests''

      '
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: default
    - continue-on-error: true
      name: run Java Testing Nexmark (query ${{ matrix.query }})
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-Pnexmark.runner=:runners:direct-java \

          "-Pnexmark.args=${{ env.GRADLE_JAVA_COMMAND_ARGUMENTS }} \

          --query=${{ matrix.query }} \

          --generateEventFilePathPrefix=gs://temp-storage-for-perf-tests/nexmark/eventFiles/beam_PostCommit_Python_Nexmark_Direct/query${{
          matrix.query }}-" \

          '
        gradle-command: :sdks:java:testing:nexmark:run
    - continue-on-error: true
      name: run Python Testing Benchmarks Nexmark (query ${{ matrix.query }})
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: '-PpythonVersion=3.8 \

          "-Pnexmark.args=${{ env.GRADLE_PYTHON_COMMAND_ARGUMENTS }} \

          --query=${{ matrix.query }} \

          --input=gs://temp-storage-for-perf-tests/nexmark/eventFiles/beam_PostCommit_Python_Nexmark_Direct/query${{
          matrix.query }}-\*"'
        gradle-command: :sdks:python:apache_beam:testing:benchmarks:nexmark:run
    strategy:
      fail-fast: false
      matrix:
        job_name:
        - beam_PostCommit_Python_Nexmark_Direct
        job_phrase:
        - Run Python Direct Runner Nexmark Tests
        query:
        - 0
        - 2
        - 3
        - 5
        - 7
        - 8
        - 10
        - 11
    timeout-minutes: 240
name: PostCommit Python Nexmark Direct
on:
  repository_dispatch:
    types: trigger-ga___beam_PostCommit_Python_Nexmark_Direct.yml
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  discussions: read
  id-token: none
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
