env:
  docker_registry: us-central1-docker.pkg.dev
  docker_repo: apache-beam-testing/beam-github-actions/beam-arc-runner
jobs:
  build-and-version-runner:
    env:
      working-directory: .github/gh-actions-self-hosted-runners/arc/images/
    if: github.repository == 'apache/beam'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      if: github.ref == 'refs/heads/master'
      name: Authenticate on GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        export_default_credentials: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - continue-on-error: true
      name: GCloud Docker credential helper
      run: 'gcloud auth configure-docker ${{env.docker_registry}}

        '
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - continue-on-error: true
      name: Build and Load to docker
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.working-directory }}
        load: true
        push: false
        tags: '${{env.docker_registry}}/${{env.docker_repo}}:latest

          ${{env.docker_registry}}/${{env.docker_repo}}:${{ github.sha }}

          '
    - continue-on-error: true
      id: docker_build
      if: github.ref == 'refs/heads/master'
      name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.working-directory }}
        push: false
        tags: '${{env.docker_registry}}/${{env.docker_repo}}:latest

          ${{env.docker_registry}}/${{env.docker_repo}}:${{ github.sha }}

          '
name: Build and Version Runner Docker Image
on:
  repository_dispatch:
    types: trigger-ga___build_runner_image.yml
