jobs:
  cancel-duplicate-workflow-runs:
    name: Cancel duplicate workflow runs
    permissions:
      actions: write
      checks: read
      contents: read
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      name: Cancel duplicate workflow runs
      uses: ./.github/actions/cancel-workflow-runs
      with:
        cancelMode: duplicates
        notifyPRCancel: true
        sourceRunId: ${{ github.event.workflow_run.id }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: Cancel
on:
  repository_dispatch:
    types: trigger-ga___cancel.yml
