env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  INTELLIJ_IDEA_SOURCES: /home/runner/work/beam/beam/intellij
jobs:
  test:
    name: Build and run model-level tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Maximize Build Space
      run: 'sudo rm -rf /usr/share/dotnet

        sudo rm -rf /usr/local/lib/android

        sudo rm -rf /opt/ghc

        '
    - continue-on-error: true
      name: Fetch beam Sources
      uses: actions/checkout@v4
      with:
        path: main
    - continue-on-error: true
      name: Fetch intellij-community Sources
      uses: actions/checkout@v4
      with:
        path: intellij
        repository: JetBrains/intellij-community
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.6
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      id: properties
      name: Export Properties
      run: 'pwd

        cd main/plugins/beam-code-completion-plugin/

        pwd

        PROPERTIES="$(./gradlew properties --console=plain -q)"

        VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d '' '')"

        NAME="$(echo "$PROPERTIES" | grep "^name:" | cut -f2- -d '' '')"


        echo "version=$VERSION" >> $GITHUB_OUTPUT

        echo "name=$NAME" >> $GITHUB_OUTPUT

        echo "pluginVerifierHomeDir=~/.pluginVerifier" >> $GITHUB_OUTPUT


        echo "changelog<<EOF" >> $GITHUB_OUTPUT

        echo "$CHANGELOG" >> $GITHUB_OUTPUT

        echo "EOF" >> $GITHUB_OUTPUT

        '
      shell: bash
    - continue-on-error: true
      name: Run Tests
      run: 'pwd

        cd main/plugins/beam-code-completion-plugin/

        pwd

        ./gradlew test --info

        '
    - continue-on-error: true
      if: ${{ failure() }}
      name: Collect Tests Result
      uses: actions/upload-artifact@v4
      with:
        name: tests-result
        path: ${{ github.workspace }}/build/reports/tests
name: Code Completion Plugin Tests
on:
  repository_dispatch:
    types: trigger-ga___code_completion_plugin_tests.yml
