concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
jobs:
  build_python_sdk_source:
    name: Build python source distribution
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - continue-on-error: true
      name: Build source
      run: pip install -U build && python -m build --sdist
      working-directory: ./sdks/python
    - continue-on-error: true
      name: Rename source file
      run: mv $(ls | grep "apache-beam.*tar\.gz\|apache_beam.*tar\.gz") apache-beam-source.tar.gz
      working-directory: ./sdks/python/dist
    - continue-on-error: true
      name: Upload compressed sources as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python_sdk_source
        path: sdks/python/dist/apache-beam-source.tar.gz
  python_unit_tests:
    name: Python Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.params.py_ver }}
    - continue-on-error: true
      name: Install tox
      run: pip install tox
    - continue-on-error: true
      name: Install SDK with dask
      run: pip install setuptools --upgrade && pip install -e .[gcp,dask,test]
      working-directory: ./sdks/python
    - continue-on-error: true
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
      name: Run tests basic unix
      run: tox -c tox.ini -e ${{ matrix.params.tox_env }}-dask
      working-directory: ./sdks/python
    - continue-on-error: true
      if: startsWith(matrix.os, 'windows')
      name: Run tests basic windows
      run: tox -c tox.ini -e ${{ matrix.params.tox_env }}-win-dask
      working-directory: ./sdks/python
    - continue-on-error: true
      if: always()
      name: Upload test logs
      uses: actions/upload-artifact@v4
      with:
        name: pytest-${{matrix.os}}-${{matrix.params.py_ver}}
        path: sdks/python/pytest**.xml
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        params:
        - py_ver: '3.8'
          tox_env: py38
        - py_ver: '3.9'
          tox_env: py39
        - py_ver: '3.10'
          tox_env: py310
name: Dask Runner Tests
on:
  repository_dispatch:
    types: trigger-ga___dask_runner_tests.yml
