env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  deploy_release_candidate_pypi:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Mask PyPi id/password
      run: '# Workaround for Actions bug - https://github.com/actions/runner/issues/643

        PYPI_API_TOKEN=$(jq -r ''.inputs.PYPI_API_TOKEN'' $GITHUB_EVENT_PATH)

        echo "::add-mask::$PYPI_API_TOKEN"

        '
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        python-version: 3.11
    - continue-on-error: true
      name: Install dependencies
      run: 'pip install python-dateutil

        pip install requests

        pip install twine

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_REPO_BASE_URL: https://github.com/apache/beam
        RC_TAG: v${{ github.event.inputs.RELEASE }}-RC${{ github.event.inputs.RC }}
        RELEASE: ${{ github.event.inputs.RELEASE }}
        RELEASE_DIR: beam/${{ github.event.inputs.RELEASE }}
        SCRIPT_DIR: release/src/main/scripts
        SVN_ARTIFACTS_DIR: beam/${{ github.event.inputs.RELEASE }}/python
      name: Deploy to Pypi
      run: "git fetch --all --tags --prune\nRELEASE_COMMIT=$(git rev-list -n 1 $RC_TAG)\n\
        \nPYTHON_ARTIFACTS_DIR=\"./python\"\npython \"release/src/main/scripts/download_github_actions_artifacts.py\"\
        \ \\\n  --github-token-var GITHUB_TOKEN \\\n  --repo-url \"apache/beam\" \\\
        \n  --rc-tag \"${RC_TAG}\" \\\n  --release-commit \"${RELEASE_COMMIT}\" \\\
        \n  --artifacts_dir \"${PYTHON_ARTIFACTS_DIR}\" \\\n  --rc_number \"${{ github.event.inputs.RC\
        \ }}\" \\\n  --yes True\n\ncd \"${PYTHON_ARTIFACTS_DIR}\"\nls\n\necho \"------Checking\
        \ Hash Value for apache_beam-${RELEASE}rc${{ github.event.inputs.RC }}.tar.gz-----\"\
        \nsha512sum -c \"apache_beam-${RELEASE}rc${{ github.event.inputs.RC }}.tar.gz.sha512\"\
        \n\nfor artifact in *.whl; do\n  echo \"----------Checking Hash Value for\
        \ ${artifact} wheel-----------\"\n  sha512sum -c \"${artifact}.sha512\"\n\
        done\n\necho \"===================Removing sha512 files=======================\"\
        \nrm $(ls | grep -i \".*.sha512$\")\n\necho \"====================Upload rc\
        \ to pypi========================\"\nmkdir dist && mv $(ls | grep apache)\
        \ dist && cd dist\necho \"Will upload the following files to PyPI:\"\nls\n\
        \ntwine upload * -u __token__ -p \"${{ github.event.inputs.PYPI_API_TOKEN\
        \ }}\"\n"
name: deploy_release_candidate_pypi
on:
  repository_dispatch:
    types: trigger-ga___deploy_release_candidate_pypi.yaml
