env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  READ_ONLY: ${{ inputs.READ_ONLY }}
jobs:
  flaky-test-detection:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - continue-on-error: true
      run: pip install PyGithub
    - continue-on-error: true
      run: python .test-infra/tools/flaky_test_detection.py
name: Flaky test detection
on:
  repository_dispatch:
    types: trigger-ga___flaky_test_detection.yml
permissions:
  issues: write
