concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
jobs:
  build:
    name: Go Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - continue-on-error: true
      uses: actions/setup-go@v5
      with:
        cache-dependency-path: 'sdks/go.sum

          '
        go-version: '1.21'
    - continue-on-error: true
      name: Delete old coverage
      run: 'cd sdks && rm -rf .coverage.txt || :'
    - continue-on-error: true
      name: Run coverage
      run: cd sdks && go test -coverprofile=coverage.txt -covermode=atomic ./go/pkg/...
        ./go/container/... ./java/container/... ./python/container/... ./typescript/container/...
    - continue-on-error: true
      uses: codecov/codecov-action@v3
      with:
        files: ./sdks/coverage.txt
        flags: go
        name: go-unittests
    - continue-on-error: true
      name: Run fmt
      run: cd sdks/go/pkg/beam && go fmt ./...; git diff-index --quiet HEAD || (echo
        "Run go fmt before checking in changes" && exit 1)
    - continue-on-error: true
      name: Run vet
      run: "cd sdks/go/pkg/beam \ngo vet --copylocks=false --unsafeptr=false ./...\n"
    - continue-on-error: true
      name: Run Staticcheck
      run: 'go install "honnef.co/go/tools/cmd/staticcheck@2023.1.3"

        cd sdks/go/pkg/beam

        $(go env GOPATH)/bin/staticcheck ./...

        '
name: Go tests
on:
  repository_dispatch:
    types: trigger-ga___go_tests.yml
