concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  check_gcp_variables:
    name: Check GCP variables set
    outputs:
      gcp-variables-set: ${{ steps.check_gcp_variables.outputs.gcp-variables-set }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PYTHON_WHEELS_BUCKET: not-needed-here
        GCP_REGION: not-needed-here
        GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        GCP_TESTING_BUCKET: ${{ secrets.GCP_TESTING_BUCKET }}
      id: check_gcp_variables
      name: Check are GCP variables set
      run: ./scripts/ci/ci_check_are_gcp_variables_set.sh
    timeout-minutes: 5
  java_unit_tests:
    name: Java Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        go-version: default
        java-version: 11
    - continue-on-error: true
      name: Run :sdks:java:core:test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: -p sdks/java/core/
        gradle-command: test
    - continue-on-error: true
      if: always()
      name: Upload test logs for :sdks:java:core:test
      uses: actions/upload-artifact@v4
      with:
        name: java_unit_tests-sdks-java-core-test-${{ matrix.os }}
        path: sdks/java/core/build/reports/tests/test
    - continue-on-error: true
      if: always()
      name: Run :sdks:java:harness:test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: -p sdks/java/harness/
        gradle-command: test
    - continue-on-error: true
      if: always()
      name: Upload test logs for :sdks:java:harness:test
      uses: actions/upload-artifact@v4
      with:
        name: java_unit_tests-sdks-java-harness-test-${{ matrix.os }}
        path: sdks/java/harness/build/reports/tests/test
    - continue-on-error: true
      if: always()
      name: Run :runners:core-java:test
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: -p runners/core-java/
        gradle-command: test
    - continue-on-error: true
      if: always()
      name: Upload test logs for :runners:core-java:test
      uses: actions/upload-artifact@v4
      with:
        name: java_unit_tests-runners-core-java-test-${{ matrix.os }}
        path: runners/core-java/build/reports/tests/test
    strategy:
      fail-fast: false
      matrix:
        os:
        - - self-hosted
          - ubuntu-20.04
          - main
        - macos-latest
        - windows-latest
  java_wordcount_dataflow:
    if: "needs.check_gcp_variables.outputs.gcp-variables-set == 'true' && (\n  (github.event_name\
      \ == 'push' || github.event_name == 'schedule') ||\n  (github.event_name ==\
      \ 'workflow_dispatch' && github.event.inputs.runDataflow == 'true')\n)\n"
    name: Java Wordcount Dataflow
    needs:
    - check_gcp_variables
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        go-version: default
        java-version: 11
    - continue-on-error: true
      name: Authenticate on GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        export_default_credentials: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - continue-on-error: true
      name: Run WordCount
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: -p examples/ --tests org.apache.beam.examples.WordCountIT -DintegrationTestPipelineOptions=[\"--runner=DataflowRunner\",\"--project=${{
          secrets.GCP_PROJECT_ID }}\",\"--tempRoot=gs://${{ secrets.GCP_TESTING_BUCKET
          }}/tmp/\"] -DintegrationTestRunner=dataflow
        gradle-command: integrationTest
    - continue-on-error: true
      if: always()
      name: Upload test logs
      uses: actions/upload-artifact@v4
      with:
        name: java_wordcount_dataflow-${{matrix.os}}
        path: examples/java/build/reports/tests/integrationTest
    strategy:
      fail-fast: false
      matrix:
        os:
        - - self-hosted
          - ubuntu-20.04
          - main
        - windows-latest
  java_wordcount_direct_runner:
    name: Java Wordcount Direct Runner
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        go-version: default
        java-version: 11
    - continue-on-error: true
      name: Run WordCount Unix
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        arguments: -p examples/ --tests org.apache.beam.examples.WordCountIT -DintegrationTestRunner=direct
          -DintegrationTestPipelineOptions=[\"--runner=DirectRunner\",\"--tempRoot=./tmp\"]
        gradle-command: integrationTest
    - continue-on-error: true
      if: always()
      name: Upload test logs
      uses: actions/upload-artifact@v4
      with:
        name: java_wordcount_direct_runner-${{matrix.os}}
        path: examples/java/build/reports/tests/integrationTest
    strategy:
      fail-fast: false
      matrix:
        os:
        - - self-hosted
          - ubuntu-20.04
          - main
        - macos-latest
        - windows-latest
name: Java Tests
on:
  repository_dispatch:
    types: trigger-ga___java_tests.yml
