jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v4
      with:
        configuration-path: .github/autolabeler.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
name: LabelPrs
on:
  repository_dispatch:
    types: trigger-ga___label_prs.yml
permissions: read-all
