concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  run_local_env_install_mac:
    name: Mac run local environment shell script
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - continue-on-error: true
      id: local_env_install_mac
      name: Installing local env dependencies
      run: ./local-env-setup.sh
    - continue-on-error: true
      id: local_env_install_gradle_check_mac
      name: Gradle check
      run: ./gradlew checkSetup
    timeout-minutes: 50
  run_local_env_install_ubuntu:
    name: Ubuntu run local environment shell script
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - continue-on-error: true
      id: local_env_install_ubuntu
      name: Installing local env dependencies
      run: sudo ./local-env-setup.sh
    - continue-on-error: true
      id: local_env_install_gradle_check_ubuntu
      name: Gradle check
      run: ./gradlew checkSetup
    timeout-minutes: 25
name: Local environment tests
on:
  repository_dispatch:
    types: trigger-ga___local_env_tests.yml
