concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  playground_frontend_test:
    env:
      FLUTTER_VERSION: 3.10.4
    name: Playground Frontend Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Flutter Dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}
        path: /opt/hostedtoolcache/flutter
        restore-keys: ${{ runner.OS }}-flutter-install-cache
    - continue-on-error: true
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ env.FLUTTER_VERSION }}
    - continue-on-error: true
      name: Install Dependencies
      run: 'cd playground_components && flutter pub get && cd ..

        cd playground_components_dev && flutter pub get && cd ..

        flutter pub get

        '
      working-directory: playground/frontend
    - continue-on-error: true
      name: Test playground_components
      run: flutter test
      working-directory: playground/frontend/playground_components
    - continue-on-error: true
      name: Test playground
      run: flutter test
      working-directory: playground/frontend
    - continue-on-error: true
      uses: nanasess/setup-chromedriver@v2
    - continue-on-error: true
      name: Integration tests
      run: 'chromedriver --port=4444 &

        ./gradlew :playground:frontend:integrationTest -PdeviceId=web-server

        '
name: Playground Frontend Test
on:
  repository_dispatch:
    types: trigger-ga___playground_frontend_test.yml
