env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  precommit_check:
    env:
      DATASTORE_EMULATOR_VERSION: 423.0.0
      JAVA_VERSION: '11'
      PYTHON_VERSION: '3.8'
    name: precommit-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out the repo
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: ${{ env.JAVA_VERSION }}
        python-version: ${{ env.PYTHON_VERSION }}
    - continue-on-error: true
      name: Add GOPATH/bin to PATH
      run: echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
    - continue-on-error: true
      name: Install sbt for running SCIO tests
      run: 'sudo apt-get update --yes

        sudo apt-get install apt-transport-https curl gnupg -yqq

        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee
        /etc/apt/sources.list.d/sbt.list

        echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list

        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823"
        | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg
        --import

        sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg

        sudo apt-get update --yes

        sudo apt-get install sbt --yes

        sudo wget https://codeload.github.com/spotify/scio.g8/zip/7c1ba7c1651dfd70976028842e721da4107c0d6d
        -O scio.g8.zip && unzip scio.g8.zip && mv scio.g8-7c1ba7c1651dfd70976028842e721da4107c0d6d
        /opt/scio.g8

        '
    - continue-on-error: true
      name: Set up Cloud SDK and its components
      uses: google-github-actions/setup-gcloud@v0
      with:
        install_components: beta,cloud-datastore-emulator
        version: ${{ env.DATASTORE_EMULATOR_VERSION }}
    - continue-on-error: true
      name: Run PreCommit
      run: ./gradlew playground:backend:precommit
name: Playground PreCommit
on:
  repository_dispatch:
    types: trigger-ga___playground_backend_precommit.yml
