jobs:
  process-prs:
    if: github.repository == 'apache/beam'
    permissions:
      checks: read
      contents: write
      issues: read
      pull-requests: write
      statuses: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - continue-on-error: true
      name: Install pr-bot npm dependencies
      run: npm ci
      working-directory: scripts/ci/pr-bot
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run processNewPrs
      working-directory: scripts/ci/pr-bot
name: pr-bot-new-prs
on:
  repository_dispatch:
    types: trigger-ga___pr-bot-new-prs.yml
