jobs:
  publish_github_release_notes:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_VERSION: ${{ github.event.inputs.RELEASE_VERSION}}
    name: Publish Github Release Notes
    needs: set-properties
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Publish github release notes
      run: "POST_PATH=\"website/www/site/content/en/blog/beam-${{env.RELEASE_VERSION}}.md\"\
        \nRELEASE_NOTES=$(\ncat ${POST_PATH} |                               # Read\
        \ post's content\nsed -n '/<!--/,$p' |                             # Remove\
        \ post's metadata\nsed -e :a -Ee 's/<!--.*-->.*//g;/<!--/N;//ba' |  # Remove\
        \ license\nsed '/./,$!d' |                                  # Remove leading\
        \ whitespace\nsed 's=](/=](https://beam.apache.org/=g'         # Replace relative\
        \ website path with absolute\n)\nESCAPED_NOTES=$(printf '%s' \"${RELEASE_NOTES}\"\
        \ | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')\nREQUEST_JSON=\"\
        $(cat <<-EOF\n{\n  \"tag_name\": \"v${RELEASE_VERSION}\",\n  \"name\": \"\
        Beam ${RELEASE_VERSION} release\",\n  \"body\": ${ESCAPED_NOTES},\n  \"generate_release_notes\"\
        : true\n}\nEOF\n)\"\necho -e \"Below is the request JSON about to be sent\
        \ to the Github API:\\n\\n ${REQUEST_JSON}\\n\\n\"\ncurl https://api.github.com/repos/apache/beam/releases\
        \ \\\n-X POST \\\n-H \"Authorization: token ${{env.GITHUB_TOKEN}}\" \\\n-H\
        \ \"Content-Type:application/json\" \\\n-d \"${REQUEST_JSON}\"\necho -e \"\
        \\n\\nView the release on Github: https://github.com/apache/beam/releases/tag/v${RELEASE_VERSION}\""
  set-properties:
    outputs:
      properties: ${{ steps.test-properties.outputs.properties }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      id: test-properties
      uses: ./.github/actions/setup-default-test-properties
name: Publish Github Release Notes
on:
  repository_dispatch:
    types: trigger-ga___publish_github_release_notes.yml
permissions: read-all
