jobs:
  assign:
    name: Generate issue report
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - continue-on-error: true
      env:
        ISSUE_REPORT_RECIPIENT_EMAIL_ADDRESS: dev@beam.apache.org
        ISSUE_REPORT_SENDER_EMAIL_ADDRESS: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_ADDRESS
          }}
        ISSUE_REPORT_SENDER_EMAIL_PASSWORD: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_PASSWORD
          }}
        ISSUE_REPORT_SENDER_EMAIL_SERVICE: gmail
      run: 'npm ci

        node generateReport.js

        '
      working-directory: scripts/ci/issue-report
name: Generate issue report
on:
  repository_dispatch:
    types: trigger-ga___reportGenerator.yml
