jobs:
  python_run_change_point_analysis:
    name: Run Change Point Analysis.
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Authenticate on GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        export_default_credentials: true
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - continue-on-error: true
      name: Install Apache Beam
      run: pip install -e .[gcp,test]
      working-directory: ./sdks/python
    - continue-on-error: true
      name: Install signal-processing-algorithms
      run: pip install signal-processing-algorithms
    - continue-on-error: true
      name: Install pandas, yaml, requests
      run: pip install pandas db-dtypes PyYAML requests
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
      name: Run Change Point Analysis.
      run: python perf_analysis.py --config_file_path=./tests_config.yaml --save_alert_metadata
      shell: bash
      working-directory: ./sdks/python/apache_beam/testing/analyzers
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'pull_request'
      name: Run Change Point Analysis.
      run: python perf_analysis.py --config_file_path=./tests_config.yaml
      shell: bash
      working-directory: ./sdks/python/apache_beam/testing/analyzers
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Run change point analysis tests.
      run: pytest perf_analysis_test.py
      shell: bash
      working-directory: ./sdks/python/apache_beam/testing/analyzers
name: Performance alerting tool on Python load/performance/benchmark tests.
on:
  repository_dispatch:
    types: trigger-ga___run_perf_alert_tool.yml
