jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-pr-message: This pull request has been closed due to lack of activity.
          If you think that is incorrect, or the pull request requires review, you
          can revive the PR at any time.
        days-before-issue-close: -1
        days-before-issue-stale: -1
        days-before-pr-close: 7
        days-before-pr-stale: 60
        exempt-pr-labels: pinned,security
        operations-per-run: 100
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-label: stale
        stale-pr-message: "This pull request has been marked as stale due to 60 days\
          \ of inactivity. It will be closed in 1 week if no further activity occurs.\
          \ If you think that\u2019s incorrect or this pull request requires a review,\
          \ please simply write any comment. If closed, you can revive the PR at any\
          \ time and @mention a reviewer or discuss it on the dev@beam.apache.org\
          \ list. Thank you for your contributions."
name: Mark and close stale pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions: read-all
