concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
env:
  DATASTORE_EMULATOR_DATADIR: ./datadir
  DATASTORE_EMULATOR_HOST: localhost:8081
  DATASTORE_PROJECT_ID: demo-test-proj
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
  GOOGLE_CLOUD_PROJECT: demo-test-proj
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  PLAYGROUND_ROUTER_HOST: localhost:8000
  PORT_GET_CONTENT_TREE: 8802
  PORT_GET_UNIT_CONTENT: 8803
  PORT_GET_USER_PROGRESS: 8804
  PORT_POST_DELETE_PROGRESS: 8807
  PORT_POST_UNIT_COMPLETE: 8805
  PORT_POST_USER_CODE: 8806
  PORT_SDK_LIST: 8801
  TOB_LEARNING_ROOT: ./samples/learning-content
jobs:
  integration:
    defaults:
      run:
        working-directory: ./learning/tour-of-beam/backend
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        go-version: '1.16'
    - continue-on-error: true
      name: Build Playground router image
      run: ./gradlew -i playground:backend:containers:router:docker
      working-directory: ${{ env.GITHUB_WORKSPACE }}
    - continue-on-error: true
      name: Start emulators
      run: docker-compose up -d
    - continue-on-error: true
      name: Compile CF
      run: go build -o ./tob_function cmd/main.go
    - continue-on-error: true
      name: Run getSdkList in background
      run: PORT=${{ env.PORT_SDK_LIST }} FUNCTION_TARGET=getSdkList ./tob_function
        &
    - continue-on-error: true
      name: Run getContentTree in background
      run: PORT=${{ env.PORT_GET_CONTENT_TREE }} FUNCTION_TARGET=getContentTree ./tob_function
        &
    - continue-on-error: true
      name: Run getUnitContent in background
      run: PORT=${{ env.PORT_GET_UNIT_CONTENT }} FUNCTION_TARGET=getUnitContent ./tob_function
        &
    - continue-on-error: true
      name: Run getUserProgress in background
      run: PORT=${{ env.PORT_GET_USER_PROGRESS }} FUNCTION_TARGET=getUserProgress
        ./tob_function &
    - continue-on-error: true
      name: Run postUnitComplete in background
      run: PORT=${{ env.PORT_POST_UNIT_COMPLETE }} FUNCTION_TARGET=postUnitComplete
        ./tob_function &
    - continue-on-error: true
      name: Run postUserCode in background
      run: PORT=${{ env.PORT_POST_USER_CODE }} FUNCTION_TARGET=postUserCode ./tob_function
        &
    - continue-on-error: true
      name: Run postDeleteProgress in background
      run: PORT=${{ env.PORT_POST_DELETE_PROGRESS }} FUNCTION_TARGET=postDeleteProgress
        ./tob_function &
    - continue-on-error: true
      name: Run CI/CD to populate datastore
      run: go run cmd/ci_cd/ci_cd.go
    - continue-on-error: true
      name: Go integration tests
      run: go test -v --tags integration ./integration_tests/...
    - continue-on-error: true
      if: always()
      name: Stop emulators
      run: docker-compose down
    - continue-on-error: true
      name: Check index.yaml
      run: 'diff -q "${{ env.DATASTORE_EMULATOR_DATADIR }}/WEB-INF/index.yaml" \

        internal/storage/index.yaml \

        || ( echo "index.yaml mismatch"; exit 1)

        '
name: Tour of Beam Go integration tests
on:
  repository_dispatch:
    types: trigger-ga___tour_of_beam_backend_integration.yml
