concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
jobs:
  checks:
    defaults:
      run:
        working-directory: ./learning/tour-of-beam/backend
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-go@v5
      with:
        go-version: '1.16'
    - continue-on-error: true
      name: Run fmt
      run: 'go fmt ./...

        git diff-index --quiet HEAD || (echo "Run go fmt before checking in changes"
        && exit 1)

        '
    - continue-on-error: true
      name: Run vet
      run: go vet ./...
    - continue-on-error: true
      name: Run test
      run: go test -v ./...
    - continue-on-error: true
      name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.49.0
        working-directory: learning/tour-of-beam/backend
name: Tour of Beam Go unittests
on:
  repository_dispatch:
    types: trigger-ga___tour_of_beam_backend.yml
