jobs:
  assign:
    name: Mark issue as triaged when assigned
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: 'ISSUE_NUMBER="$(jq ''.issue.number'' $GITHUB_EVENT_PATH)"

        REPO="$(jq ''.repository.full_name'' $GITHUB_EVENT_PATH | tr -d \")"

        curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels/awaiting%20triage

        '
      shell: bash
name: Mark issue as triaged when assigned
on:
  repository_dispatch:
    types: trigger-ga___triaged-on-assign.yml
