concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label
    || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule ||
    github.event.comment.id || github.event.sender.login}}
jobs:
  check_gcp_variables:
    name: Check GCP variables
    outputs:
      gcp-variables-set: ${{ steps.check_gcp_variables.outputs.gcp-variables-set }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_PYTHON_WHEELS_BUCKET: not-needed-here
        GCP_REGION: ${{ secrets.GCP_REGION }}
        GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        GCP_TESTING_BUCKET: ${{ secrets.GCP_TESTING_BUCKET }}
      id: check_gcp_variables
      name: Check are GCP variables set
      run: ./scripts/ci/ci_check_are_gcp_variables_set.sh
    timeout-minutes: 5
  typescript_dataflow_tests:
    if: needs.check_gcp_variables.outputs.gcp-variables-set == 'true'
    name: TypeScript Dataflow Tests
    needs:
    - check_gcp_variables
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - continue-on-error: true
      name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - continue-on-error: true
      name: Setup Beam Python
      run: 'pip install ''pandas>=1.0,<1.5''

        pip install -e ".[gcp]"

        '
      working-directory: ./sdks/python
    - continue-on-error: true
      name: Authenticate on GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        export_default_credentials: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - continue-on-error: true
      run: npm ci
      working-directory: ./sdks/typescript
    - continue-on-error: true
      run: npm run build
      working-directory: ./sdks/typescript
    - continue-on-error: true
      env:
        BEAM_SERVICE_OVERRIDES: '{"python:*": "python"}'
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ secrets.GCP_REGION }}
        GCP_TESTING_BUCKET: gs://${{ secrets.GCP_TESTING_BUCKET }}/tmp
      run: npm test -- --grep "@dataflow"
      working-directory: ./sdks/typescript
    strategy:
      fail-fast: false
  typescript_unit_tests:
    name: TypeScript Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - continue-on-error: true
      run: npm ci
      working-directory: ./sdks/typescript
    - continue-on-error: true
      run: npm run build
      working-directory: ./sdks/typescript
    - continue-on-error: true
      if: contains(matrix.os, 'ubuntu-20.04')
      run: npm run prettier-check
      working-directory: ./sdks/typescript
    - continue-on-error: true
      run: npm test
      working-directory: ./sdks/typescript
    strategy:
      fail-fast: false
      matrix:
        os:
        - - self-hosted
          - ubuntu-20.04
        - macos-latest
        - - self-hosted
          - windows-server-2019
  typescript_xlang_tests:
    name: TypeScript xlang Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - continue-on-error: true
      name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - continue-on-error: true
      name: Setup Beam Python
      run: 'pip install ''pandas>=1.0,<1.5''

        pip install -e .

        '
      working-directory: ./sdks/python
    - continue-on-error: true
      run: npm ci
      working-directory: ./sdks/typescript
    - continue-on-error: true
      run: npm run build
      working-directory: ./sdks/typescript
    - continue-on-error: true
      env:
        BEAM_SERVICE_OVERRIDES: '{"python:*": "python"}'
      run: npm test -- --grep "@xlang" --grep "@ulr"
      working-directory: ./sdks/typescript
    strategy:
      fail-fast: false
    timeout-minutes: 15
name: TypeScript Tests
on:
  repository_dispatch:
    types: trigger-ga___typescript_tests.yml
