env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
jobs:
  set-properties:
    outputs:
      properties: ${{ steps.test-properties.outputs.properties }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      id: test-properties
      uses: ./.github/actions/setup-default-test-properties
  update_python_dependencies:
    name: Update Python Dependencies
    needs: set-properties
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        go-version: default
        java-version: default
        python-version: '3.8

          3.9

          3.10

          3.11

          3.12

          '
    - continue-on-error: true
      name: Update Python Dependencies
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        gradle-command: :sdks:python:container:generatePythonRequirementsAll
    - continue-on-error: true
      name: Install gh cli
      uses: ./.github/actions/setup-gh-cli-linux
    - continue-on-error: true
      name: Set git config
      run: 'git config user.name $GITHUB_ACTOR

        git config user.email actions@"$RUNNER_NAME".local

        '
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Commit Changes and create new PR
      run: "# Take the current date, subtract from a release cut date in the past\
        \ (Mar 6, 2024),\n# then get the num days % 42 (our release cadence is 42\
        \ days).\n# This will ensure it only runs the week after a release branch\
        \ has been cut.\ndays_diff=$(( ($(date +%s) - $(date --date=\"240306\" +%s)\
        \ )/(60*60*24)%42 ))\nif [[ $days_diff -gt 6 ]]; then\n  echo \"Exiting early.\
        \ We only update dependencies the week after we cut the release\"\n  exit\
        \ 0\nfi\nbranchName=weekly_update_python_dependencies_$(date +%s)\ngit checkout\
        \ -b $branchName\ngit add -A\ngit diff-index --quiet HEAD || gitdiff=$? ||\
        \ echo $?\nif [[ $gitDiff != 0 ]]; then\n  echo \"Changes are ready to commit\"\
        \n  git commit -m \"Update Python Dependencies\" --quiet\n  git push origin\
        \ $branchName --quiet\n  GITHUB_PR_URL=$(gh pr create --title \"Update Python\
        \ Dependencies\" --label \"python\" --body \"This PR was created by automation\
        \ - by default this does not execute tests due to a limitation in GitHub Actions.\
        \ To review this PR, please (1) review the contents to make sure all dependency\
        \ upgrades are formatted correctly, (2) close and reopen the PR (3) Approve/merge\
        \ if tests pass successfully.\")\n  echo \"Link of the new PR  $GITHUB_PR_URL\"\
        \nelse\n  echo \"No changes on the files\"\nfi\n"
name: Update Python Depedencies
on:
  repository_dispatch:
    types: trigger-ga___update_python_dependencies.yml
permissions:
  checks: read
  contents: write
  issues: read
  pull-requests: write
  statuses: read
